<?php
/**
 * Created by PhpStorm.
 * User: vadim
 * Date: 14.02.16
 * Time: 21:15
 */

namespace sibds\controllers;


use yii\helpers\ArrayHelper;

class NsStandartController extends StandartController
{
    public function actions()
    {
        return ArrayHelper::merge(
            [
                'nodeMove' => [
                    'class' => 'sibds\controllers\actions\NodeMoveAction',
                ],
            ]
            , parent::actions()) ; // TODO: Change the autogenerated stub
    }
}